[package]
name = "homeapi"
version = "0.1.0"
authors = ["INAJIMA Daisuke <inajima@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
chrono = { version = "0.4", features = ["serde"] }
futures = "0.3"
lambda_runtime = "0.2"
once_cell = "1.5"
reqwest = { version = "0.10", features = ["blocking", "json"] }
rusoto_core = "0.45"
rusoto_dynamodb = "0.45"
serde = { version = "1.0", features = ["derive"] }
serde_dynamodb = "0.6"
serde_json = "1.0"
tokio = { version = "0.2", features = ["full"] }
