name: CI
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    container: ghcr.io/anyakichi/homeapi:main
    steps:
      - uses: actions/checkout@v4
      - run: cargo build
      - run: cargo test
      - run: cargo fmt --all -- --check
      - run: cargo clippy
